In [1]:
import torch 
import numpy as np 
lst = [[1,2,3], [4,5,6]]
tensor = torch.tensor(lst)

#from numpy array
np_array = np.array([1,2,4])
np_tensor = torch.from_numpy(np_array)

tensor.dtype
tensor.device

# can add mul dev sub tensors ... most np operations

device(type='cpu')

In [2]:
import torch.nn as nn 
input_tensor = torch.tensor([[0.3471,0.4547,-0.2356]])

#linear layer
linear_layer= nn.Linear(in_features=3,out_features= 2)

# return output 
output = linear_layer(input_tensor)
print(output)

tensor([[0.3135, 0.2080]], grad_fn=<AddmmBackward0>)


In [3]:
linear_layer.weight

Parameter containing:
tensor([[ 0.0137, -0.4947, -0.3276],
        [-0.3256,  0.3406, -0.3048]], requires_grad=True)

In [4]:
linear_layer.bias

Parameter containing:
tensor([0.4565, 0.0944], requires_grad=True)

In [5]:
#regression model for classification we add sigmoid or softmax
model = nn.Sequential(
    nn.Linear(10,18),
    nn.Linear(18,20),
    nn.Linear(20,5)
)
print(input_tensor)

tensor([[ 0.3471,  0.4547, -0.2356]])


In [6]:
# now we add activation function to add onon linearity
input_tensor = torch.tensor([[6.0]])
sigmoid = nn.Sigmoid()
output = sigmoid(input_tensor)# used as last step when using binary classification

# softmax used for multi class classifiaction takes n elem vect and output same size
input_tensor = torch.tensor([[4,6.0,1]])
probabilities = nn.Softmax(dim=-1)
output_tensor = probabilities(input_tensor)

print(output_tensor)

tensor([[0.1185, 0.8756, 0.0059]])


In [7]:
# forward pass to predict and give output
# backward used for updating weights 
 

In [8]:
# one hot encoding 
import torch.nn.functional as F
F.one_hot(torch.tensor(2),num_classes = 3)


tensor([0, 0, 1])

In [9]:
from torch.nn import CrossEntropyLoss
from torch import tensor

scores = tensor([[-0.1211,0.1059]])# the values of the model before activation function
one_hot_target = tensor([[1,0]])# the onehot encoding of the right class
criterion = CrossEntropyLoss()
criterion(scores.double(),one_hot_target.double())

tensor(0.8131, dtype=torch.float64)

In [10]:
import torch
import torch.nn as nn
import torch.optim as optim

# Define model
model = nn.Sequential(
    nn.Linear(10, 18),
    nn.ReLU(),  # Adding non-linearity
    nn.Linear(18, 20),
    nn.ReLU(),
    nn.Linear(20, 5)
)

# Define input data and targets
input_data = torch.randn(100, 10)  # Example: 100 samples, 10 features
targets = torch.randint(0, 5, (100,))  # Example: 100 targets, 5 classes

# Forward pass
outputs = model(input_data)

# Compute loss
criterion = nn.CrossEntropyLoss()
loss = criterion(outputs, targets)

# Backward pass
loss.backward()

# Extract gradients
gradients = []
for param in model.parameters():
    if param.grad is not None:
        gradients.append(param.grad.view(-1))
gradients = torch.cat(gradients)

# Print or use gradients
print((gradients))


tensor([-3.8745e-03, -2.9625e-03,  4.6295e-03,  8.2846e-04,  6.0182e-03,
        -4.7606e-03,  1.4616e-03,  4.1604e-03,  2.4318e-03, -2.5598e-04,
         2.0931e-03, -1.5537e-03, -8.0914e-04,  2.5300e-03,  3.4674e-03,
        -1.6253e-03,  2.1685e-03, -7.4808e-04,  4.2180e-03, -3.1880e-03,
        -4.4371e-03,  1.5576e-03, -1.7497e-03,  2.4522e-03,  4.7469e-03,
        -5.5151e-06,  1.7311e-03, -3.2607e-04, -1.2925e-03,  9.1881e-04,
         6.2203e-04, -1.0011e-03, -7.0800e-04,  1.6719e-03,  3.4598e-04,
         1.1780e-03, -1.3271e-03, -1.0800e-03,  5.2166e-04,  1.3043e-03,
        -2.9848e-03,  2.9658e-04, -5.0549e-03, -8.4453e-03, -9.7727e-03,
         2.0801e-03, -8.0685e-03, -2.3645e-04, -4.8065e-03,  4.2095e-03,
         4.4672e-03, -1.9033e-03, -3.2240e-03,  8.0816e-03, -4.4857e-03,
         1.7254e-03,  1.4479e-03, -8.0130e-03,  2.9207e-03,  2.8712e-03,
        -2.0194e-03, -4.2629e-04, -3.9377e-03, -1.5123e-03, -2.2006e-03,
         4.6726e-03, -3.1863e-03,  8.6314e-04, -2.9

The first linear layer (`nn.Linear(10, 18)`) has \(10 \times 18\) weights and 18 biases, totaling \(10 \times 18 + 18 = 198\) parameters.
The second linear layer (`nn.Linear(18, 20)`) has \(18 \times 20\) weights and 20 biases, totaling \(18 \times 20 + 20 = 380\) parameters.
The third linear layer (`nn.Linear(20, 5)`) has \(20 \times 5\) weights and 5 biases, totaling \(20 \times 5 + 5 = 105\) parameters.


In [11]:
# Define optimizer
optimizer = optim.SGD(model.parameters(), lr=0.01)

# Update model parameters
optimizer.step()

# Clear gradients
optimizer.zero_grad()


## to do it manually 
weight0 = model[0].weight

weight1 = model[1].weight

weight2 = model[2].weight

Access the gradients of the weight of each linear layer

grads0 = weight0.grad

grads1 = weight1.grad

grads2 = weight2.grad

Update the weights using the learning rate and the gradients

weight0 =weight0- lr*grads0

weight1 =weight1- lr*grads1

weight2 = weight2-lr*grads2

In [12]:
updated_outputs = model(input_data)
loss = criterion(updated_outputs, targets)

# Backward pass
loss.backward()

# Extract gradients
gradients = []
for param in model.parameters():
    if param.grad is not None:
        gradients.append(param.grad.view(-1))
gradients = torch.cat(gradients)
print(gradients)

tensor([-3.9086e-03, -2.9293e-03,  4.6748e-03,  7.5734e-04,  6.1277e-03,
        -4.7397e-03,  1.1582e-03,  4.3618e-03,  2.2591e-03, -2.9529e-04,
         2.0973e-03, -1.5508e-03, -8.1232e-04,  2.5363e-03,  3.4681e-03,
        -1.6269e-03,  2.1729e-03, -7.5294e-04,  4.2224e-03, -3.1883e-03,
        -4.4115e-03,  1.5361e-03, -1.7820e-03,  2.5023e-03,  4.6675e-03,
        -1.7953e-05,  1.9421e-03, -4.7243e-04, -1.1722e-03,  9.5211e-04,
         6.2117e-04, -1.0043e-03, -7.0707e-04,  1.6694e-03,  3.4579e-04,
         1.1768e-03, -1.3227e-03, -1.0751e-03,  5.2322e-04,  1.3007e-03,
        -2.9618e-03,  2.7850e-04, -5.0822e-03, -8.3966e-03, -9.8636e-03,
         2.0700e-03, -7.8524e-03, -3.8764e-04, -4.6836e-03,  4.2378e-03,
         4.4721e-03, -1.9108e-03, -3.2290e-03,  8.0898e-03, -4.4935e-03,
         1.7252e-03,  1.4669e-03, -8.0240e-03,  2.9363e-03,  2.8707e-03,
        -2.0191e-03, -4.2979e-04, -3.9457e-03, -1.5092e-03, -2.1893e-03,
         4.6655e-03, -3.1833e-03,  8.5809e-04, -2.9

In [13]:
updated_outputs

tensor([[ 1.2139e-01, -2.1565e-01, -1.5174e-01, -6.9622e-02,  1.3354e-01],
        [ 1.4627e-01, -1.3089e-01, -1.5582e-01,  9.7402e-03,  1.3720e-01],
        [ 9.0151e-02, -1.4322e-01, -2.1309e-01,  2.9169e-02,  2.6267e-01],
        [ 1.6294e-01, -2.5998e-01, -4.4575e-02, -8.5716e-02,  1.0176e-01],
        [ 1.9883e-01, -1.9001e-01, -1.4166e-01, -4.4087e-02,  1.5521e-01],
        [ 1.6569e-01, -1.5531e-01, -1.6349e-01, -8.5988e-03,  1.2282e-01],
        [ 1.2570e-01, -2.1066e-01, -5.2862e-02, -8.1039e-02,  2.4847e-03],
        [ 1.6965e-01, -2.0882e-01, -1.9724e-01,  1.9199e-02,  2.4841e-01],
        [ 1.1911e-01, -2.2902e-01, -1.1128e-01, -1.1262e-01,  6.0103e-02],
        [ 1.1484e-01, -2.1097e-01, -1.3596e-01, -5.1027e-02,  1.8778e-01],
        [ 2.3638e-01, -1.4357e-01, -1.4383e-01,  4.4006e-02,  1.8750e-01],
        [ 1.0246e-01, -1.7679e-01, -1.6548e-01, -4.6357e-02,  1.6594e-01],
        [ 1.0391e-01, -1.7545e-01, -1.8134e-01, -4.3168e-02,  1.7868e-01],
        [ 1.5279e-01, -1.

In [14]:
targets

tensor([4, 0, 4, 2, 3, 4, 2, 2, 1, 2, 2, 0, 1, 2, 2, 4, 3, 0, 2, 2, 1, 3, 2, 0,
        1, 0, 0, 2, 3, 4, 2, 1, 1, 3, 2, 4, 4, 3, 3, 4, 3, 3, 3, 3, 2, 3, 1, 3,
        0, 1, 0, 4, 0, 2, 0, 3, 0, 2, 3, 2, 0, 4, 2, 4, 4, 0, 4, 4, 3, 3, 3, 4,
        4, 2, 1, 2, 2, 4, 1, 1, 4, 4, 0, 2, 2, 2, 1, 0, 3, 0, 4, 4, 3, 1, 4, 3,
        0, 4, 4, 3])

In [15]:
torch.save(model.state_dict(), 'updated_model.pth')
model.load_state_dict(torch.load('updated_model.pth'))

<All keys matched successfully>

# the training loop

let's do it for regression problem 

In [17]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader

features = torch.randn(1000, 10)
labels = torch.randn(1000)

dataset = TensorDataset(features, labels)

batch_size = 32
shuffle = True
num_workers = 4
data_loader = DataLoader(dataset, batch_size=batch_size, shuffle=shuffle, num_workers=num_workers)

model = nn.Sequential(
    nn.Linear(10, 32),
    nn.ReLU(),
    nn.Linear(32, 1)
)

criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

num_epochs = 10
for epoch in range(num_epochs):
    running_loss = 0.0
    for batch_features, batch_labels in data_loader:
        optimizer.zero_grad()
        outputs = model(batch_features)
        loss = criterion(outputs.squeeze(), batch_labels.float())
        loss.backward()
        optimizer.step()
        running_loss += loss.item()
    print(f"Epoch {epoch+1}, Loss: {running_loss/len(data_loader)}")


Epoch 1, Loss: 0.9845340074971318
Epoch 2, Loss: 0.962383781094104
Epoch 3, Loss: 0.976639011874795
Epoch 4, Loss: 0.99384387396276
Epoch 5, Loss: 0.9766926039010286
Epoch 6, Loss: 0.998492281883955
Epoch 7, Loss: 0.9557647313922644
Epoch 8, Loss: 0.9578550774604082
Epoch 9, Loss: 0.9598546903580427
Epoch 10, Loss: 0.949790159240365


between layers activation functions 

In [ ]:
relu = lambda x:max(x,0) # it overcomes the vaniching garidient problem
# that apprears when using sigmoid 
relunn = nn.ReLU()

# leaky relu for pos the same as relu for neg it multiplies them
# by a small coeff defaulted to 0.01 like this grad has non null value 
# for neg values
leaky =nn.LeakyReLU(negative_slope=0.05)

In [ ]:
sgd = optim.SGD(model.parameters(),lr=0.01,momentum=0.95)
# the momentum controls the inertia of the optimizer which 
# helps escape the local min
# the momentom keeps the step size large when previous is large
# even if gradient is small typically between 0.85 to 0.99


In [2]:

import torch.nn as nn
# we can initialize the layer weight with any dist
layer = nn.Linear(64,128)
nn.init.uniform_(layer.weight)

print(layer.weight.min(),layer.weight.max())

tensor(2.3246e-06, grad_fn=<MinBackward1>) tensor(0.9999, grad_fn=<MaxBackward1>)


In [4]:
print(layer.weight.min(),layer.weight.max())

tensor(2.3246e-06, grad_fn=<MinBackward1>) tensor(0.9999, grad_fn=<MaxBackward1>)


Transfer learning : usinf a model traing on a first task for a second similar task to accelerate the training process

- example we train a model on big dataset for salries in us and we retrain it on a small dataset for europ so the coefficient have initial values of us which will make it converge quickly

fine tuning is a type of transfer learing: we laod weights from previous model then we use smaller learning rate
 - not evry layer is trained ( we freeze some)
 - rule of themb: freeze early layers of netw and fine-tune layers close to output 

In [ ]:
for name,param in model.named_parameters():
    if name =="0.weight":
        param.requires_grad = False

we have calculated the training loss before 
no we calculate the validation loss 